lsst-sitcom/summit_utils

python/lsst/summit/utils/__init__.py, python/lsst/summit/utils/astrometry/anet.py, python/lsst/summit/utils/astrometry/plotting.py, python/lsst/summit/utils/astrometry/utils.py, python/lsst/summit/utils/bestEffort.py, python/lsst/summit/utils/butlerUtils.py, python/lsst/summit/utils/nightReport.py, python/lsst/summit/utils/utils.py, tests/SConscript, tests/test_nightReport.py, tests/test_utils.py
Realistically now mostly other urgent fix-ups which had to be done while I had this ticket open and deployed on the summit.
=> DM-37309: Nominally bring NightReport channel online

python/lsst/summit/utils/bestEffort.py, python/lsst/summit/utils/butlerUtils.py
=> DM-32940: Use the new Butler.exists API, replacing datasetExists

tests/test_butlerUtils.py
Previously the repository index look up system was not being caught properly and so the RuntimeError printed through from the Config code. Now we catch this problem internally and allow the requested repo alias to be used. This changes the exception type being caught in the test.
Requires lsst/daf_butler#849
=> DM-39563: Test now raises FileNotFoundError

setup.cfg
This wasn't updated by the lsst/lsst-dm org automation.
=> Update flake8/pytest sections in setup.cfg.

python/lsst/summit/utils/__init__.py, python/lsst/summit/utils/assessPeekExposure.py, python/lsst/summit/utils/peekExposure.py
Adds `PeekExposureTask` as a solution to quickly find the brightest source (for observing scripts), and also quickly estimate PSF moments along xy, altaz, and equitorial axes.
=> DM-36211: Add PeekExposureTask

python/lsst/summit/utils/peekExposure.py
- Computes median/mode of pixel values _before_ subtracting the background
- Keeps the original exposure unmodified
=> DM-42874 : Tweak PeekExposureTask

python/lsst/summit/utils/tmaUtils.py, tests/test_tmaUtils.py
This is the initial commit.  I think it is all working, but would like your comments, Merlin.  Here is a plot of a tracking event.
=> DM-42039: Add TMA mount tracking errors to TMA mount motion profile

python/lsst/summit/utils/astrometry/utils.py, python/lsst/summit/utils/utils.py
Also fixes bitrot from config changes upstream and updates to astropy.
=> DM-43141: Fix StarTracker analysis to work with new headers

python/lsst/summit/utils/consdbClient.py, python/lsst/summit/utils/utils.py, tests/test_consdbClient.py, tests/test_utils.py
compute_exposure_id and compute_ccdexposure_id generate unique numeric ids locally without a server round-trip, since summit_utils already depends on afw.
compute_fixed_metadata_namespace is useful for generating query strings.
insert_multiple allows many rows to be inserted at once (e.g. for many detectors in a focal plane).
=> DM-44387: Add several convenience methods.

.github/workflows/mypy_check.yaml, mypy.ini, python/lsst/summit/utils/nightReport.py, python/lsst/summit/utils/quickLook.py, python/lsst/summit/utils/utils.py, types.txt
Review data typing in summit_utils and add mypy data checking on PR
=> DM-44751: Add mypy check as required GHA before merging

python/lsst/summit/utils/consdbClient.py, tests/test_consdbClient.py
Added test to check initialization of ConsDbClient and to test that the url is sanitized according to our terms.
=> Redact tokens/passwords from URLs in ConsDbClient HTTPError reports

python/lsst/summit/utils/tmaUtils.py
Google says that the ticks and ticklabels from mdates.AutoDateLocator() and mdates.DateFormatter("%H:%M:%S") can disappear if there are changes to the axes after invoking them.  Moving this block of code to the end recovered the time labels.
=> DM-47781: Fix to missing time ticks and ticklabels

python/lsst/summit/utils/tmaUtils.py
There has been an ongoing problem with single point errors in the TMA data stream.  These are explained in more detail in chapter “Single point errors in the tracking data stream” of [TMA tracking jitter and settling time analysis](https://sitcomtn-112.lsst.io/)  .  Julen of Tekniker has now added additional time stamps so that each data stream has it’s own timestamp.  This should eliminate those errors.  This ticket will implement the use of those new timestamps in the RubinTV tracking error plots, which should eliminat the need for the filterBadValues code.
=> DM-47874: Use new timestamps in TMA tracking errors

python/lsst/summit/utils/consdbClient.py
Handle empty result sets gracefully in ConsDbClient.query by returning an empty astropy.table.Table with the correct column names when no data is present. The current implementation of ConsDbClient.query (and other similar) raises a ValueError when the query result contains no rows, due to a mismatch between the number of column names and data columns passed to astropy.table.Table. This occurs because an empty list of rows is provided, while names may still contain column names.
=> DM-50185 Handle the case where no rows are returned in ConsDbClient.

python/lsst/summit/utils/consdbClient.py
Though it's possible to use ConsDbClient from outside of RSP by adding a token to the URL, this patch allows the user to pass the token through the HTTP header as an alternative.
=> DM-50161 Add token as an optional constructor parameter in ConsDbClient.

python/lsst/summit/utils/simonyi/mountAnalysis.py, python/lsst/summit/utils/simonyi/mountData.py
DM47874 added new timestamps to TMA tracking errors in the RubinTV TMA channel.  This eliminated the need to filter out bad values. This ticket does the same for the Mount torques plots in the LSSTCam channel.  These plots are still showing filtered values.
=> DM-50939: Eliminate the need to filterBadValues

python/lsst/summit/utils/simonyi/mountAnalysis.py
There have been several recent exposures where the images were obviously streaked, but the RubinTV Mount Torque plots reported no issue.  This is because the difference between the demand position and the actual position was small because the demand position was not doing what it should.  Examples are 2025051900417, where the mount was not tracking, and 2025052000321, where the rotator was still moving rapidly during the exposure.  Plots and images attached.  In both cases the Mount motion image degradation reported a small value even though the images were unacceptable.  The idea is to install a simplified MTPtg model in the mount analysis code in summit_utils to try and flag these.  This code seems to do that.
=> DM-51096: Use toy pointing model to calculate mount error

python/lsst/summit/utils/simonyi/mountAnalysis.py
Here's the failure and the same image after the fix.  I ran many images at a variety of azimuths, and I think it is fixed now.
=> DM-51845: Fix azimuth wrapping issue

python/lsst/summit/utils/consdbClient.py
Currently, trying to update rows in a table using the existing insert endpoint does not work, if the table's primary keys are day_obs + seq_num. This resolves that problem by adding an additional endpoint for ConsDbClient to call in that case.
=> OSW-22: Allow ConsDbClient.insert to use the by_seq_num endpoint.

python/lsst/summit/utils/simonyi/mountAnalysis.py
Adding a better way to calculate the hexapod RMS values, trying to eliminate all of the yellow values.
=> DM-52072: Switch to using reported hexapod errors
